platform :ios, '9.0'

workspace 'OutletsExample'

use_frameworks!
inhibit_all_warnings!

target 'OutletsExample' do
  pod 'Outlets', path: '../', inhibit_warnings: false
  
  target 'OutletsExampleTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end
end
